# Generated by Django 3.1 on 2024-11-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_or_emotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='twitter_handel',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
